[package]
name = "homebrew-rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "brew-rust"
path = "src/main.rs"

[dependencies]
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
